//! Tier C generated tests — Parser (49 cases).
//!
//! AUTO-GENERATED by scripts/gen-tier-c.py from the Python reference test
//! files under /home/rxx/helen/tests/parser/. Expected values are produced by the
//! Python reference implementation; the Rust pipeline must reproduce them.
//! Do not edit by hand — regenerate with: python3 scripts/gen-tier-c.py

#![allow(non_snake_case)]

use helen_core::ast_printer::AstPrinter;
use helen_core::lexer::Scanner;
use helen_parser::Parser;

fn parse_print(src: &str) -> (String, Vec<String>) {
    let mut sc = Scanner::new(src, "<test>");
    let toks = sc.scan_all();
    let mut p = Parser::new(toks);
    let prog = p.parse();
    let pr = AstPrinter::new();
    let codes = p.errors().iter().map(|e| format!("E{:04}", e.code().value())).collect();
    (pr.print_program(&prog), codes)
}

#[test]
fn t0_src_0() {
    let src = "";
    let (printed, errs) = parse_print(src);
    let expected = "(program)";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t1_llm_act__prompt__on_tool_136a8ac() {
    let src = "llm act \"prompt\" on_tool_end fn(name, result) { return null }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"prompt\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t2_llm_act__Hello__e093f5() {
    let src = "llm act \"Hello\"";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t3_llm_act__Hello__on_chunk_5767ee6() {
    let src = "llm act \"Hello\" on_chunk my_callback";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\" my_callback))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t4_llm_act__Hello__on_compl_5b21c2e() {
    let src = "llm act \"Hello\" on_complete done_fn";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\" done_fn))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t5_llm_act__Hello__on_chunk_363cd12() {
    let src = "llm act \"Hello\" on_chunk cb1 on_complete cb2";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\" cb1 cb2))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t6_let_result___llm_act__He_3f19f7() {
    let src = "let result = llm act \"Hello\" on_chunk my_cb";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let result = (llm-act \"Hello\" my_cb)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t7_llm_act_5d6bc39() {
    let src = "llm act";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act <none>))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t8_llm_act_on_chunk_my_call_21dd1c9() {
    let src = "llm act on_chunk my_callback";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act <none> my_callback))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t9_llm_act_on_complete_on_d_3593f0e() {
    let src = "llm act on_complete on_done";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act <none> on_done))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t10_llm_act_on_chunk_cb1_on__48eebba() {
    let src = "llm act on_chunk cb1 on_complete cb2";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act <none> cb1 cb2))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t11_llm_act__Hello__on_chunk_a5d379() {
    let src = "llm act \"Hello\" on_chunk fn(chunk) { print(chunk) }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\" (lambda)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t12_src_0() {
    let src = "";
    let (printed, errs) = parse_print(src);
    let expected = "(program)";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t13_llm_act__Hello__on_compl_28539b0() {
    let src = "llm act \"Hello\" on_complete on_done";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\" on_done))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t14_llm_act__Hello__on_chunk_1d5de6c() {
    let src = "llm act \"Hello\" on_chunk on_chunk on_complete on_done";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\" on_chunk on_done))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t15_llm_act__Hello__e093f5() {
    let src = "llm act \"Hello\"";
    let (printed, errs) = parse_print(src);
    let expected = "(program (llm-act \"Hello\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t16_src_0() {
    let src = "";
    let (printed, errs) = parse_print(src);
    let expected = "(program)";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t17__________54414a0() {
    let src = "   \n\t  \n";
    let (printed, errs) = parse_print(src);
    let expected = "(program)";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t18_agent_Test___prompt__hel_5ddc3d9() {
    let src = "agent Test { prompt \"hello\" }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent Test \"hello\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t19_let_x___42_d70a76() {
    let src = "let x = 42";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = 42))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t20_const_MAX___100_59a5a30() {
    let src = "const MAX = 100";
    let (printed, errs) = parse_print(src);
    let expected = "(program (const MAX = 100))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t21_let_x___1___2_4a519d5() {
    let src = "let x = 1 + 2";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = (+ 1 2)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t22_let_msg____hello__1a2a1bc() {
    let src = "let msg = \"hello\"";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let msg = \"hello\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t23_break_2cc9cef() {
    let src = "break";
    let (printed, errs) = parse_print(src);
    let expected = "(program (break))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t24_continue_5db4aa8() {
    let src = "continue";
    let (printed, errs) = parse_print(src);
    let expected = "(program (continue))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t25_return_42_4b2ae9b() {
    let src = "return 42";
    let (printed, errs) = parse_print(src);
    let expected = "(program (return 42))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t26_return_31847ad() {
    let src = "return";
    let (printed, errs) = parse_print(src);
    let expected = "(program (return))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t27_let_x___1___2___3_b78b30() {
    let src = "let x = 1 + 2 * 3";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = (+ 1 (* 2 3))))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t28_let_x____1___2____3_31034cf() {
    let src = "let x = (1 + 2) * 3";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = (* (group (+ 1 2)) 3)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t29_let_x____true_51598ef() {
    let src = "let x = !true";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = (! true)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t30_let_x___a____b_50cf4ee() {
    let src = "let x = a <= b";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = (<= a b)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t31_let_x___a____b____c_4cc90de() {
    let src = "let x = a && b || c";
    let (printed, errs) = parse_print(src);
    let expected = "(program (let x = (|| (&& a b) c)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t32_agent_A___prompt__p__mai_40b9c62() {
    let src = "agent A { prompt \"p\" main { let x = 1 } }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent A \"p\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t33_agent_Bot___prompt__You__30843b() {
    let src = "agent Bot { prompt \"You are a bot\" main { let x = 42 } }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent Bot \"You are a bot\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t34_agent_A___prompt____line_3f20b75() {
    let src = "agent A { prompt \"\"\"line1\nline2\"\"\" main { } }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent A \"line1\nline2\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t35_agent_A___prompt__a____a_20f47d() {
    let src = "agent A { prompt \"a\" } agent B { prompt \"b\" }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent A \"a\") (agent B \"b\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t36_if__true______1aeb57a() {
    let src = "if (true) { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (if true (main-block)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t37_if__true______else_____1341721() {
    let src = "if (true) { } else { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (if true (main-block) (main-block)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t38_for_x_in_items_____17c5546() {
    let src = "for x in items { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (for x items (main-block)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t39_while__true______3b20e5a() {
    let src = "while (true) { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (while true (main-block)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t40_while_true_____1646c9f() {
    let src = "while true { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (while true (main-block)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t41_while_x___10_____316d1ea() {
    let src = "while x < 10 { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (while (< x 10) (main-block)))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t42_fn_add_a__b___int___retu_420179d() {
    let src = "fn add(a, b): int { return a + b }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (fn add))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t43_fn_greet_name______322a259() {
    let src = "fn greet(name) { }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (fn greet))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t44_import__utils_helen__as__b08d36() {
    let src = "import \"utils.helen\" as utils";
    let (printed, errs) = parse_print(src);
    let expected = "(program (import utils.helen))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t45_import__config_json__2460486() {
    let src = "import \"config.json\"";
    let (printed, errs) = parse_print(src);
    let expected = "(program (import config.json))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}

#[test]
fn t46_agent_A_______prompt__he_445c4b6() {
    let src = "agent A { @@@ prompt \"hello\" }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent A))";
    assert_eq!(printed, expected, "AST printer mismatch");
    let exp_codes: Vec<String> = vec!["E0301".to_string()];
    assert_eq!(errs, exp_codes, "parse error codes");
}

#[test]
fn t47_agent_A___prompt__hello__4cb7b3() {
    let src = "agent A { prompt \"hello\"";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent A \"hello\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    let exp_codes: Vec<String> = vec!["E0301".to_string()];
    assert_eq!(errs, exp_codes, "parse error codes");
}

#[test]
fn t48_agent_A___prompt__p__mai_dbb6e6() {
    let src = "agent A { prompt \"p\" main { } }";
    let (printed, errs) = parse_print(src);
    let expected = "(program (agent A \"p\"))";
    assert_eq!(printed, expected, "AST printer mismatch");
    assert!(errs.is_empty(), "unexpected parse errors");
}
