[package]
name = "helen-interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Helen language Rust reimplementation — helen-interpreter (M3 interpreter core)"

[dependencies]
helen-core = { version = "0.1.0", path = "../helen-core" }
helen-semantic = { version = "0.1.0", path = "../helen-semantic" }
helen-parser = { version = "0.1.0", path = "../helen-parser" }
helen-runtime = { version = "0.1.0", path = "../helen-runtime" }
num-bigint.workspace = true
num-traits.workspace = true
indexmap.workspace = true
serde_json.workspace = true
csv.workspace = true
digest.workspace = true
ureq.workspace = true
regex.workspace = true
base64.workspace = true
chrono.workspace = true
rand.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true
hmac.workspace = true
uuid.workspace = true
mime_guess = "2.0"
serde_yaml = "0.9.34"
quick-xml = "0.41.0"
toml = "0.8"

[dev-dependencies]
ryu = { workspace = true }
rstest = { workspace = true }
proptest = { workspace = true }
