//! Tier C generated tests — Lexer (67 cases).
//!
//! AUTO-GENERATED by scripts/gen-tier-c.py from the Python reference test
//! files under /home/rxx/helen/tests/lexer/. Expected values are produced by the
//! Python reference implementation; the Rust pipeline must reproduce them.
//! Do not edit by hand — regenerate with: python3 scripts/gen-tier-c.py

use helen_core::errors::ErrorCode;
use helen_core::lexer::Scanner;
use helen_core::tokens::TokenType;

fn scan_tokens(src: &str) -> (Vec<(TokenType, String)>, Vec<(ErrorCode, String)>) {
    let mut s = Scanner::new(src, "<test>");
    let toks = s.scan_all();
    let pairs = toks.iter().map(|t| (t.kind, t.lexeme.clone())).collect();
    let errs = s.errors().iter().map(|e| (e.code(), e.message().to_string())).collect();
    (pairs, errs)
}

#[test]
fn t0_src_0() {
    let src = "";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t1_____412532a() {
    let src = "   ";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t2_____573e5df() {
    let src = "\n\n\n";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t3____________ef01da() {
    let src = "  \t \n \r  \n";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t4_IF_18639fc() {
    let src = "IF";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "IF".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t5_if__ee38ad() {
    let src = "if(";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::If, "if".to_string()),
        (TokenType::LeftParen, "(".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t6_max_turns_332ca34() {
    let src = "max-turns";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::MaxTurns, "max-turns".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t7_x___y_4ecb103() {
    let src = "x - y";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "x".to_string()),
        (TokenType::Minus, "-".to_string()),
        (TokenType::Identifier, "y".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t8_foo__19b85e1() {
    let src = "foo-";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Minus, "-".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t9_true_false_null_493344d() {
    let src = "true false null";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::True, "true".to_string()),
        (TokenType::False, "false".to_string()),
        (TokenType::NullKw, "null".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t10_foo_2745521() {
    let src = "foo";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t11__private_3eecffc() {
    let src = "_private";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "_private".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t12_myVariable_517df8c() {
    let src = "myVariable";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "myVariable".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t13_var123_19ee0da() {
    let src = "var123";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "var123".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t14_foo_bar_baz_359d89c() {
    let src = "foo bar baz";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Identifier, "bar".to_string()),
        (TokenType::Identifier, "baz".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t15_42_752af1() {
    let src = "42";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "42".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t16_0_1d5aa5e() {
    let src = "0";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "0".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t17_3_14_54ac842() {
    let src = "3.14";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "3.14".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t18__5_48cc04d() {
    let src = ".5";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, ".5".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t19_42__b5d5f6() {
    let src = "42.";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "42.".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t20_1e10_42818b3() {
    let src = "1e10";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "1e10".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t21_1e_5_891bf8() {
    let src = "1e-5";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "1e-5".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t22_2E_3_4ce443a() {
    let src = "2E+3";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "2E+3".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t23_1_000_000_55e2dba() {
    let src = "1_000_000";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "1_000_000".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t24_1_000_5_be179e() {
    let src = "1_000.5";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "1_000.5".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t25_1__2__3_421b5cb() {
    let src = "1, 2, 3";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "1".to_string()),
        (TokenType::Comma, ",".to_string()),
        (TokenType::Number, "2".to_string()),
        (TokenType::Comma, ",".to_string()),
        (TokenType::Number, "3".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t26____2ac948d() {
    let src = "\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t27__hello__329cf00() {
    let src = "\"hello\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"hello\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t28__line1_nline2__2f455e2() {
    let src = "\"line1\\nline2\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"line1\\nline2\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t29__col1_tcol2__4b4eef7() {
    let src = "\"col1\\tcol2\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"col1\\tcol2\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t30__a__b__3f65c97() {
    let src = "\"a\\\\b\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"a\\\\b\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t31__say___hi____463755c() {
    let src = "\"say \\\"hi\\\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"say \\\"hi\\\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t32__tab_there_n__5d1b1dc() {
    let src = "\"tab\\there\\n\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"tab\\there\\n\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t33__hello_world___e67bfb() {
    let src = "\"hello world!\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::String, "\"hello world!\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t34____hello____d2fcae() {
    let src = "\"\"\"hello\"\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TripleQuoteString, "\"\"\"hello\"\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t35____line1_line2_line3____3e37390() {
    let src = "\"\"\"line1\nline2\nline3\"\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TripleQuoteString, "\"\"\"line1\nline2\nline3\"\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t36____hello_nworld____50456b() {
    let src = "\"\"\"hello\\nworld\"\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TripleQuoteString, "\"\"\"hello\\nworld\"\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t37________2ca70f1() {
    let src = "\"\"\"\"\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TripleQuoteString, "\"\"\"\"\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t38_______________5cdf5e8() {
    let src = "+ - * / % ! |";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Plus, "+".to_string()),
        (TokenType::Minus, "-".to_string()),
        (TokenType::Star, "*".to_string()),
        (TokenType::Slash, "/".to_string()),
        (TokenType::Percent, "%".to_string()),
        (TokenType::Bang, "!".to_string()),
        (TokenType::Pipe, "|".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t39_______5070016() {
    let src = "== !=";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::EqualEqual, "==".to_string()),
        (TokenType::BangEqual, "!=".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t40___________15b72f9() {
    let src = "< > <= >=";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Less, "<".to_string()),
        (TokenType::Greater, ">".to_string()),
        (TokenType::LessEqual, "<=".to_string()),
        (TokenType::GreaterEqual, ">=".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t41_______9f4765() {
    let src = "&& ||";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::And, "&&".to_string()),
        (TokenType::Or, "||".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t42___1381d37() {
    let src = "=";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Assign, "=".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t43____3425f47() {
    let src = "->";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Arrow, "->".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t44_______________________26a3075() {
    let src = "( ) { } [ ] , . : ; ?";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::LeftParen, "(".to_string()),
        (TokenType::RightParen, ")".to_string()),
        (TokenType::LeftBrace, "{".to_string()),
        (TokenType::RightBrace, "}".to_string()),
        (TokenType::LeftBracket, "[".to_string()),
        (TokenType::RightBracket, "]".to_string()),
        (TokenType::Comma, ",".to_string()),
        (TokenType::Dot, ".".to_string()),
        (TokenType::Colon, ":".to_string()),
        (TokenType::Semicolon, ";".to_string()),
        (TokenType::Question, "?".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t45____this_is_a_comment_42_cf61a() {
    let src = "// this is a comment\n42";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "42".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t46____comment_981da2() {
    let src = "// comment";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t47____comment____42_4654d0() {
    let src = "/* comment */ 42";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "42".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t48____line1_line2____42_8dbd4d() {
    let src = "/* line1\nline2 */ 42";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "42".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t49____outer____inner________5191e56() {
    let src = "/* outer /* inner */ */ 42";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "42".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t50_foo____skip____bar_21a3ccf() {
    let src = "foo /* skip */ bar";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Identifier, "bar".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t51_foo___bar_4dc2f09() {
    let src = "foo   bar";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Identifier, "bar".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t52_foo__bar_1d92edf() {
    let src = "foo\t\nbar";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Identifier, "bar".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t53______foo_3d9148f() {
    let src = "  \n  foo";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t54___var___2c457e8() {
    let src = "{{var}}";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TemplateOpen, "{{".to_string()),
        (TokenType::Identifier, "var".to_string()),
        (TokenType::TemplateClose, "}}".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t55___name___3c41815() {
    let src = "{{name}}";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TemplateOpen, "{{".to_string()),
        (TokenType::Identifier, "name".to_string()),
        (TokenType::TemplateClose, "}}".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t56______1686f56() {
    let src = "{{}}";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TemplateOpen, "{{".to_string()),
        (TokenType::TemplateClose, "}}".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t57___foo_1d3c22b() {
    let src = "~ foo";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
    assert_eq!(errs.len(), 1, "error count");
}

#[test]
fn t58_foo_bar_3e24352() {
    let src = "foo\nbar";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Identifier, "bar".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t59___foo_302f558() {
    let src = "  foo";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t60____line1_line2____20f9714() {
    let src = "\"\"\"line1\nline2\"\"\"";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::TripleQuoteString, "\"\"\"line1\nline2\"\"\"".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t61_12345_1a57332() {
    let src = "12345";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Number, "12345".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t62_x_2d3d493() {
    let src = "x";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Identifier, "x".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t63__foo_46e3224() {
    let src = ".foo";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Dot, ".".to_string()),
        (TokenType::Identifier, "foo".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t64__5_26b5e99() {
    let src = "-5";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Minus, "-".to_string()),
        (TokenType::Number, "5".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t65___8350b3() {
    let src = "|";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Pipe, "|".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}

#[test]
fn t66____18d3b9e() {
    let src = "||";
    let (toks, errs) = scan_tokens(src);
    let expected: Vec<(TokenType, String)> = vec![
        (TokenType::Or, "||".to_string()),
        (TokenType::Eof, "".to_string()),
    ];
    assert_eq!(toks.len(), expected.len(), "token count");
    for (got, want) in toks.iter().zip(expected.iter()) {
        assert_eq!(got.0, want.0, "kind mismatch");
        assert_eq!(got.1, want.1, "lexeme mismatch");
    }
}
