#![allow(non_snake_case)]
//! Tier C generated tests — Semantic (21 cases).
//!
//! AUTO-GENERATED by scripts/gen-tier-c.py from the Python reference test
//! files under /home/rxx/helen/tests/semantic/. Expected values are produced by the
//! Python reference implementation; the Rust pipeline must reproduce them.
//! Do not edit by hand — regenerate with: python3 scripts/gen-tier-c.py

use helen_core::lexer::Scanner;
use helen_parser::Parser;
use helen_semantic::analyze_codes;

fn analyze_codes_of(src: &str) -> Vec<String> {
    let mut sc = Scanner::new(src, "<test>");
    let toks = sc.scan_all();
    let mut p = Parser::new(toks);
    let prog = p.parse();
    analyze_codes(&prog)
}

#[test]
fn t0_src_0() {
    let src = "";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t1_let__buf______agent_Test_4b72b7f() {
    let src = "let _buf = \"\"\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = _buf  // ❌ module-level variable not visible in agent\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0350".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t2_let__buf______agent_Test_4d0bfe1() {
    let src = "let _buf = \"\"\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        _buf = \"new\"  // ❌ cannot assign to module-level variable\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0350".to_string(), "E0350".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t3_const_LIMIT___100_agent__4f32a56() {
    let src = "const LIMIT = 100\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = LIMIT  // ✅ const is read-only shared across agents\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t4_let__buf______fn__helper_5170de7() {
    let src = "let _buf = \"\"\nfn _helper(): str {\n    return _buf  // ✅ functions see module-level variables\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t5_fn__helper____str________1a99308() {
    let src = "fn _helper(): str {\n    return \"ok\"\n}\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = _helper()  // ✅ calling functions is fine\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t6_agent_TestAgent_______de_10ffb68() {
    let src = "agent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = len(\"hello\")  // ✅ stdlib is injected into agent env\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0332".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t7_agent_TestAgent_______de_2866ad2() {
    let src = "agent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = 42  // ✅ local to agent main\n        let y = x + 1\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t8_let__buf______fn__buf_re_1798477() {
    let src = "let _buf = \"\"\nfn _buf_reset() { _buf = \"\" }\nfn _buf_get(): str { return _buf }\n\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        _buf_reset()  // ✅ via function\n        let x = _buf_get()  // ✅ via function\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t9_let__router_buf______age_1fb3cf4() {
    let src = "let _router_buf = \"\"\nagent QuestionRouter {\n    description \"test\"\n    prompt \"test\"\n    main {\n        _router_buf = \"\"  // ❌\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0350".to_string(), "E0350".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t10_let__a______let__b_______2a1b29e() {
    let src = "let _a = \"\"\nlet _b = \"\"\nagent AgentA {\n    description \"a\"\n    prompt \"a\"\n    main {\n        _a = \"x\"  // ❌ triggers both read + write scope errors\n    }\n}\nagent AgentB {\n    description \"b\"\n    prompt \"b\"\n    main {\n        _b = \"y\"  // ❌ triggers both read + write scope errors\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![
        "E0350".to_string(),
        "E0350".to_string(),
        "E0350".to_string(),
        "E0350".to_string(),
    ];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t11_const_LIMIT___100_const__56fca03() {
    let src = "const LIMIT = 100\nconst NAME = \"Helen\"\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = LIMIT  // ✅ const is read-only shared\n        let y = NAME   // ✅ const is read-only shared\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t12_const_LIMIT___100_agent__1d6fa63() {
    let src = "const LIMIT = 100\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        LIMIT = 200  // ❌ const is read-only\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0346".to_string(), "E0350".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t13_shared_let__buf______age_5cdcebf() {
    let src = "shared let _buf = \"\"\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = _buf  // ✅ shared let is cross-agent visible\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t14_shared_let__buf______age_a36898() {
    let src = "shared let _buf = \"\"\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        _buf = \"new\"  // ✅ shared let is writable across agents\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t15_shared_const_LIMIT___100_56320e9() {
    let src = "shared const LIMIT = 100\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = LIMIT  // ✅ shared const is read-only shared\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t16_let__buf______agent_Test_3f24b66() {
    let src = "let _buf = \"\"\nagent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let x = _buf  // ❌ plain let is not cross-agent\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0350".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t17_agent_TestAgent_______de_298b502() {
    let src = "agent TestAgent {\n    description \"test\"\n    prompt \"test\"\n    main {\n        let buf = \"\"\n        let cb = fn(chunk) {\n            buf = buf + chunk\n        }\n        llm act \"hello\" on_chunk cb\n    }\n}\n";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t18_src_0() {
    let src = "";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t19_main___print__a_____main_55a38dd() {
    let src = "main { print(\"a\") }\nmain { print(\"b\") }";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec!["E0332".to_string(), "E0332".to_string()];
    assert_eq!(got, expected, "E-code mismatch");
}

#[test]
fn t20_let_x___42_d70a76() {
    let src = "let x = 42";
    let got = analyze_codes_of(src);
    let expected: Vec<String> = vec![];
    assert_eq!(got, expected, "E-code mismatch");
}
