//! Build script: embed all files under `skills/` into the binary via
//! `include_str!` so that bundled skills work after `cargo install`
//! (where `CARGO_MANIFEST_DIR` no longer points to a real directory).
//!
//! Generates `$OUT_DIR/embedded_skills.rs` with:
//!   - `embedded_skill_file(rel_path) -> Option<&'static str>`
//!   - `embedded_skill_paths() -> &'static [&'static str]`

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let skills_dir = PathBuf::from("skills");
    if !skills_dir.is_dir() {
        // No skills directory — generate empty stubs.
        let out = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out).join("embedded_skills.rs");
        let mut f = fs::File::create(&dest).unwrap();
        writeln!(f, "pub fn embedded_skill_file(_: &str) -> Option<&'static str> {{ None }}").unwrap();
        writeln!(f, "pub fn embedded_skill_paths() -> &'static [&'static str] {{ &[] }}").unwrap();
        return;
    }

    // Collect all files under skills/.
    let mut files: Vec<PathBuf> = Vec::new();
    collect_files(&skills_dir, &mut files);
    files.sort();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("embedded_skills.rs");
    let mut f = fs::File::create(&dest).unwrap();

    // Absolute path to skills dir for include_str! (resolved at compile time).
    let abs_skills = fs::canonicalize(&skills_dir).expect("skills dir must exist");

    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(f, "// Embeds {} skill files via include_str!.", files.len()).unwrap();
    writeln!(f).unwrap();

    // Generate embedded_skill_file() match arms.
    writeln!(
        f,
        "pub fn embedded_skill_file(rel_path: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(f, "    match rel_path {{").unwrap();
    for file in &files {
        let rel = file.strip_prefix(&skills_dir).unwrap().to_string_lossy();
        // Use forward slashes for cross-platform consistency.
        let rel_unix = rel.replace('\\', "/");
        let abs_path = abs_skills.join(file.strip_prefix(&skills_dir).unwrap());
        let abs_str = abs_path.to_string_lossy();
        writeln!(
            f,
            "        {:?} => Some(include_str!({:?})),",
            rel_unix, abs_str
        )
        .unwrap();
    }
    writeln!(f, "        _ => None,").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    // Generate embedded_skill_paths() — sorted list of all relative paths.
    writeln!(
        f,
        "pub fn embedded_skill_paths() -> &'static [&'static str] {{"
    )
    .unwrap();
    writeln!(f, "    &[").unwrap();
    for file in &files {
        let rel = file
            .strip_prefix(&skills_dir)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        writeln!(f, "        {:?},", rel).unwrap();
    }
    writeln!(f, "    ]").unwrap();
    writeln!(f, "}}").unwrap();

    // Tell cargo to rerun if any skill file changes.
    println!("cargo:rerun-if-changed=skills");
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(&path, out);
            } else if path.is_file() {
                out.push(path);
            }
        }
    }
}
