//! Auto-generated stdlib catalog (M4 Task 4.1).
//! Source: Python `helen/stdlib/__init__.py` registration tables.
//! Regenerate: `python3 scripts/extract_builtins.py`.

/// A catalog entry for docgen / registry metadata.
pub struct BuiltinCatalogEntry {
    pub name: &'static str,
    pub description: &'static str,
    pub signature: &'static str,
    pub category: &'static str,
}

/// All 378 canonical builtins, sorted by name.
pub static BUILTIN_CATALOG: &[BuiltinCatalogEntry] = &[
    BuiltinCatalogEntry {
        name: "abs",
        description: "Absolute value",
        signature: "abs(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "acos",
        description: "Arc cosine",
        signature: "acos(x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "after_all",
        description: "Register after-all hook",
        signature: "after_all(fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "after_each",
        description: "Register after-each hook",
        signature: "after_each(fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "analyze_code",
        description: "Analyze code metrics",
        signature: "analyze_code(source, filename?)",
        category: "quality",
    },
    BuiltinCatalogEntry {
        name: "append_file",
        description: "Append to file",
        signature: "append_file(path, content)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "asin",
        description: "Arc sine",
        signature: "asin(x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "assert_contains",
        description: "Assert container contains item",
        signature: "assert_contains(container, item, message?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "assert_equal",
        description: "Assert equality",
        signature: "assert_equal(actual, expected, message?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "assert_not_equal",
        description: "Assert inequality",
        signature: "assert_not_equal(actual, expected, message?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "assert_throws",
        description: "Assert function throws",
        signature: "assert_throws(fn, error_type?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "assert_true",
        description: "Assert condition is truthy",
        signature: "assert_true(condition, message?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "atan",
        description: "Arc tangent",
        signature: "atan(x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "atan2",
        description: "Arc tangent of y/x",
        signature: "atan2(y, x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "base64_decode",
        description: "Base64 decode",
        signature: "base64_decode(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "base64_encode",
        description: "Base64 encode",
        signature: "base64_encode(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "before_all",
        description: "Register before-all hook",
        signature: "before_all(fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "before_each",
        description: "Register before-each hook",
        signature: "before_each(fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "bit_and",
        description: "Bitwise AND",
        signature: "bit_and(a, b)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "bit_not",
        description: "Bitwise NOT",
        signature: "bit_not(a)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "bit_or",
        description: "Bitwise OR",
        signature: "bit_or(a, b)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "bit_shift_left",
        description: "Bitwise left shift",
        signature: "bit_shift_left(a, n)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "bit_shift_right",
        description: "Bitwise right shift",
        signature: "bit_shift_right(a, n)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "bit_xor",
        description: "Bitwise XOR",
        signature: "bit_xor(a, b)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "bool",
        description: "Convert to boolean",
        signature: "bool(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "calculate",
        description: "Evaluate math expression",
        signature: "calculate(expression)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "cancel_all_llm_calls",
        description: "Cancel all active streaming LLM calls",
        signature: "cancel_all_llm_calls()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "cancel_llm_call",
        description: "Cancel an in-flight streaming LLM call",
        signature: "cancel_llm_call(call_id)",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "ceil",
        description: "Ceiling value",
        signature: "ceil(value)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "center",
        description: "Center string",
        signature: "center(s, width, char?)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "check_security",
        description: "Check security issues",
        signature: "check_security(source)",
        category: "quality",
    },
    BuiltinCatalogEntry {
        name: "choice",
        description: "Choose random item",
        signature: "choice(items)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "chr",
        description: "Unicode code point to character",
        signature: "chr(code)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "chunk",
        description: "Split into chunks",
        signature: "chunk(lst, size)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "cleanup_sessions",
        description: "Clean up old sessions (v1.23.7: cascade=true deletes spawned)",
        signature: "cleanup_sessions(keep_count?, older_than_days?, cascade?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "clear_context",
        description: "Clear conversation context",
        signature: "clear_context()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "compress_context",
        description: "Compress conversation context",
        signature: "compress_context(strategy?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "compress_context_target",
        description: "Compress context by target type",
        signature: "compress_context_target(target, keep_recent?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "contains",
        description: "Check if contains substring",
        signature: "contains(s, sub)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "context_slice",
        description: "Extract a slice of conversation history",
        signature: "context_slice(start?, end?, role?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "context_stats",
        description: "Return detailed statistics about current context",
        signature: "context_stats()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "context_usage",
        description: "Return current context usage ratio (0.0-1.0)",
        signature: "context_usage()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "copy_file",
        description: "Copy file",
        signature: "copy_file(src, dst)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "correlation",
        description: "Pearson correlation",
        signature: "correlation(x, y)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "cos",
        description: "Cosine",
        signature: "cos(radians)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "count",
        description: "Count substring",
        signature: "count(s, sub)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "coverage_off",
        description: "Disable coverage tracking",
        signature: "coverage_off()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "coverage_on",
        description: "Enable coverage tracking",
        signature: "coverage_on()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "coverage_report",
        description: "Generate coverage report",
        signature: "coverage_report(format?)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "coverage_summary",
        description: "Get coverage summary",
        signature: "coverage_summary()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "cpu_count",
        description: "Get CPU core count",
        signature: "cpu_count()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "csv_load",
        description: "Load CSV from file",
        signature: "csv_load(path, delimiter?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "csv_parse",
        description: "Parse CSV",
        signature: "csv_parse(text, delimiter?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "csv_save",
        description: "Save CSV to file",
        signature: "csv_save(path, rows, delimiter?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "csv_stringify",
        description: "Stringify to CSV",
        signature: "csv_stringify(rows, delimiter?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "current_llm_call_id",
        description: "Get the current active streaming call ID",
        signature: "current_llm_call_id()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "date",
        description: "Create/get date",
        signature: "date(year?, month?, day?)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_add",
        description: "Add to date",
        signature: "date_add(date_str, days?, hours?, minutes?, seconds?)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_day",
        description: "Extract day",
        signature: "date_day(date_str)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_diff",
        description: "Date difference",
        signature: "date_diff(date1, date2, unit?)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_format",
        description: "Format date",
        signature: "date_format(date_str, format_str)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_month",
        description: "Extract month",
        signature: "date_month(date_str)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_parse",
        description: "Parse date",
        signature: "date_parse(date_str, format_str)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_weekday",
        description: "Day of week",
        signature: "date_weekday(date_str)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "date_year",
        description: "Extract year",
        signature: "date_year(date_str)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "datetime",
        description: "Create/get datetime",
        signature: "datetime(year?, month?, day?, hour?, minute?, second?)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "debug",
        description: "Output structured debug info",
        signature: "debug(message, data?)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "delete_current_session",
        description: "Permanently delete current session (v1.23.7: cascade=true deletes spawned)",
        signature: "delete_current_session(confirm?, cascade?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "delete_dir",
        description: "Delete directory",
        signature: "delete_dir(path, recursive?)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "delete_file",
        description: "Delete file",
        signature: "delete_file(path)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "delete_message",
        description: "Delete a message by UUID",
        signature: "delete_message(uuid)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "delete_session",
        description: "Permanently delete a session (v1.23.7: cascade=true deletes spawned sessions)",
        signature: "delete_session(session_id, cascade?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "describe",
        description: "Define a test suite",
        signature: "describe(name, fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "dict",
        description: "Convert to dict or create empty dict",
        signature: "dict(value?)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "endswith",
        description: "Check suffix",
        signature: "endswith(s, suffix)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "entries",
        description: "Get dict entries",
        signature: "entries(dict)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "env_delete",
        description: "Delete environment variable",
        signature: "env_delete(key)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "env_get",
        description: "Get environment variable",
        signature: "env_get(key, default?)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "env_list",
        description: "List all environment variables",
        signature: "env_list()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "env_set",
        description: "Set environment variable",
        signature: "env_set(key, value)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "error_category",
        description: "Extract diagnostic category from error dict",
        signature: "error_category(err)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "error_data_flow",
        description: "Extract data flow from error dict",
        signature: "error_data_flow(err)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "error_suggestion",
        description: "Extract suggestion from error dict",
        signature: "error_suggestion(err)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "every",
        description: "Check all elements",
        signature: "every(lst, fn)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "exec",
        description: "Execute command",
        signature: "exec(command, shell?, timeout?)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "exec_async",
        description: "Execute command asynchronously",
        signature: "exec_async(command, shell?)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "exit",
        description: "Exit program",
        signature: "exit(code?)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "exp",
        description: "Exponential (e^x)",
        signature: "exp(x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "expect",
        description: "Create chainable expectation",
        signature: "expect(value)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "export_context",
        description: "Export current context as serializable dict",
        signature: "export_context()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "export_transcript",
        description: "Export transcript to file (v1.23.7: include_spawned)",
        signature: "export_transcript(output_path, format?, session_id?, include_spawned?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "extract_emails",
        description: "Extract emails",
        signature: "extract_emails(text)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "extract_urls",
        description: "Extract URLs",
        signature: "extract_urls(text)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "fail",
        description: "Explicitly fail a test",
        signature: "fail(message?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "file_modified",
        description: "File modification time",
        signature: "file_modified(path)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "file_size",
        description: "File size in bytes",
        signature: "file_size(path)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "filter",
        description: "Filter list by predicate",
        signature: "filter(lst, fn)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "find",
        description: "Find substring index",
        signature: "find(s, sub)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "find_from",
        description: "Find substring from position",
        signature: "find_from(s, sub, start)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "find_if",
        description: "Find element by predicate",
        signature: "find_if(lst, fn)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "flatten",
        description: "Flatten nested lists",
        signature: "flatten(lst)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "float",
        description: "Convert to float",
        signature: "float(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "floor",
        description: "Floor value",
        signature: "floor(value)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "fork_context",
        description: "Create a deep-copy snapshot of current context",
        signature: "fork_context()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "format_float",
        description: "Format float with decimals",
        signature: "format_float(value, decimals)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "fromtimestamp",
        description: "Unix timestamp to datetime",
        signature: "fromtimestamp(timestamp)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "get",
        description: "Get value with default",
        signature: "get(dict, key, default?)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "get_call_stack",
        description: "Get current call stack",
        signature: "get_call_stack()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "get_cli_args",
        description: "Get CLI arguments",
        signature: "get_cli_args()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "get_compression_audit",
        description: "Get compression event history",
        signature: "get_compression_audit()",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_context_config",
        description: "Get current context management config",
        signature: "get_context_config()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "get_data_lineage",
        description: "Get the complete data lineage graph",
        signature: "get_data_lineage()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "get_description",
        description: "Get agent description (read-only)",
        signature: "get_description()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_invocation",
        description: "Get metadata for a specific invocation",
        signature: "get_invocation(invocation_id, session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_invocation_tree",
        description: "Get the full invocation tree for a session (agent calls)",
        signature: "get_invocation_tree(session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_last_error",
        description: "Get last error snapshot with context",
        signature: "get_last_error()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "get_llm_log",
        description: "Get recent LLM call audit log",
        signature: "get_llm_log(n?)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "get_max_tokens",
        description: "Get effective max-tokens",
        signature: "get_max_tokens()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_max_turns",
        description: "Get effective max-turns",
        signature: "get_max_turns()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_message",
        description: "Retrieve a message by UUID",
        signature: "get_message(uuid)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "get_model",
        description: "Get current model (read-only)",
        signature: "get_model()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_provider",
        description: "Get current provider (read-only)",
        signature: "get_provider()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_reasoning_effort",
        description: "Get effective reasoning-effort",
        signature: "get_reasoning_effort()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_session_dir",
        description: "Get resolved transcript session directory",
        signature: "get_session_dir()",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_session_id",
        description: "Get current transcript session ID",
        signature: "get_session_id()",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_session_meta",
        description: "Get session metadata (argv, timestamp, version)",
        signature: "get_session_meta(session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_spawn_tree",
        description: "Get the full session spawn tree (nested spawns)",
        signature: "get_spawn_tree(session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_spawned_sessions",
        description: "Get sessions spawned by the given session",
        signature: "get_spawned_sessions(session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "get_temperature",
        description: "Get effective temperature",
        signature: "get_temperature()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_thinking_mode",
        description: "Get effective thinking-mode",
        signature: "get_thinking_mode()",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "get_trace",
        description: "Get recent execution trace",
        signature: "get_trace(n?)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "glob_files",
        description: "Recursively find files matching glob pattern",
        signature: "glob_files(path, pattern?)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "grep_files",
        description: "Search file contents for a pattern",
        signature: "grep_files(path, pattern, regex?, case_sensitive?, max_results?)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "has_key",
        description: "Check key exists",
        signature: "has_key(dict, key)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "hash_file",
        description: "Calculate hash of file",
        signature: "hash_file(path, algorithm?)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "hmac_sha256",
        description: "Calculate HMAC-SHA256",
        signature: "hmac_sha256(key, message)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "hostname",
        description: "Get hostname",
        signature: "hostname()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "html_escape",
        description: "HTML escape",
        signature: "html_escape(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "html_links",
        description: "Extract HTML links",
        signature: "html_links(html)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "html_parse",
        description: "Parse HTML",
        signature: "html_parse(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "html_select",
        description: "CSS select elements",
        signature: "html_select(html, selector)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "html_text",
        description: "Extract HTML text",
        signature: "html_text(html)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "html_unescape",
        description: "HTML unescape",
        signature: "html_unescape(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "http_delete",
        description: "HTTP DELETE request",
        signature: "http_delete(url, headers?)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "http_download",
        description: "Download file from URL",
        signature: "http_download(url, path)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "http_get",
        description: "HTTP GET request",
        signature: "http_get(url, headers?)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "http_post",
        description: "HTTP POST request",
        signature: "http_post(url, data?, headers?)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "http_put",
        description: "HTTP PUT request",
        signature: "http_put(url, data?, headers?)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "import_context",
        description: "Import a previously exported context",
        signature: "import_context(data)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "index",
        description: "Find substring index",
        signature: "index(s, sub)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "input",
        description: "Read line from stdin",
        signature: "input(prompt?)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "insert_message",
        description: "Insert a new message into context",
        signature: "insert_message(role, content, position?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "int",
        description: "Convert to integer",
        signature: "int(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "interpolate",
        description: "Template string interpolation",
        signature: "interpolate(template, vars)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "invocation_path",
        description: "Get human-readable path string for an invocation",
        signature: "invocation_path(invocation_id, session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "is_audio",
        description: "Check if MediaPart is audio",
        signature: "is_audio(value)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "is_image",
        description: "Check if MediaPart is an image",
        signature: "is_image(value)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "is_media",
        description: "Check if value is MediaPart",
        signature: "is_media(value)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "is_video",
        description: "Check if MediaPart is a video",
        signature: "is_video(value)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "isinstance",
        description: "Type check",
        signature: "isinstance(value, type_name)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "it",
        description: "Define a test case",
        signature: "it(name, fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "it_skip",
        description: "Define a skipped test case",
        signature: "it_skip(name, fn?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "join",
        description: "Join strings",
        signature: "join(items, sep)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "json_load",
        description: "Load JSON from file",
        signature: "json_load(path)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "json_parse",
        description: "Parse JSON",
        signature: "json_parse(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "json_parse_lenient",
        description: "Parse JSON with markdown fence stripping",
        signature: "json_parse_lenient(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "json_save",
        description: "Save JSON to file",
        signature: "json_save(path, value, indent?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "json_stringify",
        description: "Stringify to JSON",
        signature: "json_stringify(value, indent?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "keys",
        description: "Get dict keys",
        signature: "keys(dict)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "kill",
        description: "Send signal to process",
        signature: "kill(pid, signal?)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "last_error_detail",
        description: "Get detailed error with diagnostic category and suggestion",
        signature: "last_error_detail()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "len",
        description: "Return length of string/list/dict",
        signature: "len(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "levenshtein",
        description: "Edit distance",
        signature: "levenshtein(s1, s2)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "list",
        description: "Convert to list or create empty list",
        signature: "list(iterable?)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "list_dir",
        description: "List directory",
        signature: "list_dir(path, pattern?)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "list_invocations",
        description: "List invocations with optional filtering",
        signature: "list_invocations(session_id?, agent?, limit?, offset?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "list_pinned_messages",
        description: "List all pinned messages (uuid, role, snippet)",
        signature: "list_pinned_messages()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "list_sessions",
        description: "List all transcript sessions",
        signature: "list_sessions()",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "list_skill_references",
        description: "List reference documents for a skill",
        signature: "list_skill_references(name)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "load_skill",
        description: "Load a skill by name",
        signature: "load_skill(name, include_references?)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "log",
        description: "Logarithm",
        signature: "log(x, base?)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "log10",
        description: "Base-10 logarithm",
        signature: "log10(x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "log2",
        description: "Base-2 logarithm",
        signature: "log2(x)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "log_critical",
        description: "Log critical message",
        signature: "log_critical(message)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "log_debug",
        description: "Log debug message",
        signature: "log_debug(message)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "log_error",
        description: "Log error message",
        signature: "log_error(message)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "log_info",
        description: "Log info message",
        signature: "log_info(message)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "log_set_level",
        description: "Set logging level",
        signature: "log_set_level(level)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "log_to_file",
        description: "Set log output to file",
        signature: "log_to_file(path)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "log_warn",
        description: "Log warning message",
        signature: "log_warn(message)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "lower",
        description: "Lowercase string",
        signature: "lower(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "mailbox_select",
        description: "Receive first available message from multiple channels",
        signature: "mailbox_select(channels, timeout?)",
        category: "concurrency",
    },
    BuiltinCatalogEntry {
        name: "make_set",
        description: "Create set",
        signature: "make_set(items)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "map",
        description: "Map function over list",
        signature: "map(lst, fn)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "markdown_extract_headings",
        description: "Extract Markdown headings",
        signature: "markdown_extract_headings(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "markdown_parse",
        description: "Parse Markdown to blocks",
        signature: "markdown_parse(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "markdown_to_html",
        description: "Convert Markdown to HTML",
        signature: "markdown_to_html(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "max",
        description: "Maximum value",
        signature: "max(*args)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "md5",
        description: "Calculate MD5 hash",
        signature: "md5(text)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "mean",
        description: "Arithmetic mean",
        signature: "mean(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "media",
        description: "Create media from file/URL/MediaPart (passthrough + multi-arg)",
        signature: "media(source|MediaPart, ...) | media(source, type?)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "media_base64",
        description: "Create media from base64 data",
        signature: "media_base64(data, mime, type?)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "media_to_base64",
        description: "Convert MediaPart content to base64 string",
        signature: "media_to_base64(part)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "media_type",
        description: "Get media type",
        signature: "media_type(value)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "median",
        description: "Median value",
        signature: "median(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "memory_info",
        description: "Get memory information",
        signature: "memory_info()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "merge",
        description: "Merge dicts",
        signature: "merge(*dicts)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "min",
        description: "Minimum value",
        signature: "min(*args)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "mkdir",
        description: "Create directory",
        signature: "mkdir(path)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "mkdir_p",
        description: "Create directory tree",
        signature: "mkdir_p(path)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "mode",
        description: "Most frequent values",
        signature: "mode(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "move_file",
        description: "Move file",
        signature: "move_file(src, dst)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "multiline_input",
        description: "Read multiple lines (empty line ends)",
        signature: "multiline_input(prompt?)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "normalize_whitespace",
        description: "Normalize whitespace",
        signature: "normalize_whitespace(text)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "now",
        description: "Current datetime",
        signature: "now()",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "omit",
        description: "Omit dict keys",
        signature: "omit(dict, keys)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "on_compression",
        description: "Register callback for compression events",
        signature: "on_compression(callback?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "on_context_overflow",
        description: "Register callback for context overflow",
        signature: "on_context_overflow(callback?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "ord",
        description: "Character to Unicode code point",
        signature: "ord(char)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "pad_left",
        description: "Pad left",
        signature: "pad_left(s, width, char?)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "pad_right",
        description: "Pad right",
        signature: "pad_right(s, width, char?)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "parse_cli_args",
        description: "Parse CLI arguments",
        signature: "parse_cli_args(spec?)",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "patch_file",
        description: "Patch a file",
        signature: "patch_file(path, old_string, new_string, replace_all?)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "path_basename",
        description: "Base name",
        signature: "path_basename(path)",
        category: "path",
    },
    BuiltinCatalogEntry {
        name: "path_dirname",
        description: "Directory name",
        signature: "path_dirname(path)",
        category: "path",
    },
    BuiltinCatalogEntry {
        name: "path_exists",
        description: "Check if path exists",
        signature: "path_exists(path)",
        category: "path",
    },
    BuiltinCatalogEntry {
        name: "path_is_dir",
        description: "Check if path is directory",
        signature: "path_is_dir(path)",
        category: "path",
    },
    BuiltinCatalogEntry {
        name: "path_is_file",
        description: "Check if path is file",
        signature: "path_is_file(path)",
        category: "path",
    },
    BuiltinCatalogEntry {
        name: "path_join",
        description: "Join path components",
        signature: "path_join(*parts)",
        category: "path",
    },
    BuiltinCatalogEntry {
        name: "percentile",
        description: "Percentile value",
        signature: "percentile(numbers, p)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "pick",
        description: "Pick dict keys",
        signature: "pick(dict, keys)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "pid",
        description: "Get current process ID",
        signature: "pid()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "pin_message",
        description: "Pin a message by UUID (immune to compression)",
        signature: "pin_message(uuid)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "platform",
        description: "Get OS name",
        signature: "platform()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "platform_version",
        description: "Get detailed platform info",
        signature: "platform_version()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "pow",
        description: "Power",
        signature: "pow(base, exponent)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "print",
        description: "Print values to stdout",
        signature: "print(*args)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "product",
        description: "Product of numbers",
        signature: "product(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "progress_bar",
        description: "Display progress bar",
        signature: "progress_bar(current, total, width?)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "python_version",
        description: "Get Python version",
        signature: "python_version()",
        category: "system",
    },
    BuiltinCatalogEntry {
        name: "quality_report",
        description: "Generate quality report",
        signature: "quality_report(source, filename?)",
        category: "quality",
    },
    BuiltinCatalogEntry {
        name: "quality_score",
        description: "Calculate quality score",
        signature: "quality_score(source, file_path?)",
        category: "quality",
    },
    BuiltinCatalogEntry {
        name: "query_transcript",
        description: "Query transcript with filtering and pagination (v1.40+)",
        signature: "query_transcript(session_id?, role?, agent?, invocation_id?, since?, until?, content_regex?, message_type?, limit?, offset?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "randint",
        description: "Generate random integer",
        signature: "randint(min, max)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "random",
        description: "Generate random float",
        signature: "random()",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "random_base64",
        description: "Generate random base64 string",
        signature: "random_base64(n)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "random_bytes",
        description: "Generate random bytes as hex",
        signature: "random_bytes(n)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "random_hex",
        description: "Generate random hex string",
        signature: "random_hex(n)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "range",
        description: "Integer range",
        signature: "range(start, stop?, step?)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "read_file",
        description: "Read file content",
        signature: "read_file(path)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "record_data_flow",
        description: "Manually record a data flow event",
        signature: "record_data_flow(producer_uuid, consumer_uuid, flow_type, metadata?)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "record_session",
        description: "Start recording LLM interactions to cassette",
        signature: "record_session(cassette_path)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "reduce",
        description: "Reduce list to value",
        signature: "reduce(lst, fn, initial?)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "regex_findall",
        description: "Regex find all",
        signature: "regex_findall(pattern, s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "regex_match",
        description: "Regex match at start",
        signature: "regex_match(pattern, s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "regex_replace",
        description: "Regex replace",
        signature: "regex_replace(pattern, s, replacement)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "regex_search",
        description: "Regex search anywhere",
        signature: "regex_search(pattern, s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "regex_split",
        description: "Regex split",
        signature: "regex_split(pattern, s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "regex_test",
        description: "Regex test returns bool",
        signature: "regex_test(pattern, s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "release_session_lock",
        description: "Release cross-process session lock (called on actor exit to prevent stale locks)",
        signature: "release_session_lock(session_id)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "remove_key",
        description: "Remove single key",
        signature: "remove_key(dict, key)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "remove_punctuation",
        description: "Remove punctuation",
        signature: "remove_punctuation(text)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "repeat",
        description: "Repeat string",
        signature: "repeat(s, n)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "replace",
        description: "Replace substring",
        signature: "replace(s, old, new)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "replace_message",
        description: "Replace a message's content by UUID",
        signature: "replace_message(uuid, new_content)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "replay_full_session",
        description: "Replay transcript from session and all spawned sessions (v1.23.7+)",
        signature: "replay_full_session(session_id?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "replay_session",
        description: "Replay LLM interactions from cassette",
        signature: "replay_session(cassette_path)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "replay_transcript",
        description: "Replay transcript messages with optional invocation filtering",
        signature: "replay_transcript(session_id?, include_compressed?, agent?, invocation_id?, last_only?, include_subtree?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "restore_context",
        description: "Restore active context from a previous transcript session",
        signature: "restore_context(session_id, invocation_id?, agent?, last_only?, include_subtree?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "resume_session",
        description: "Resume a previous transcript session",
        signature: "resume_session(session_id)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "reverse",
        description: "Reverse string",
        signature: "reverse(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "round",
        description: "Round number",
        signature: "round(value, ndigits?)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "run_tests",
        description: "Execute all tests and print report",
        signature: "run_tests(only?, suite?, filter?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "run_tests_json",
        description: "Execute tests and return JSON",
        signature: "run_tests_json(only?, suite?, filter?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "sample",
        description: "Sample items randomly",
        signature: "sample(items, k)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "save_media",
        description: "Save MediaPart to file",
        signature: "save_media(part, path?)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "search_context",
        description: "Search context for messages matching query",
        signature: "search_context(query, role?, limit?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "search_transcript",
        description: "Search transcript messages by content (v1.23.7: include_spawned)",
        signature: "search_transcript(query, session_id?, scope?, role?, regex?, limit?, include_spawned?)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "set_cache_aware",
        description: "Enable/disable cache-aware compression at runtime",
        signature: "set_cache_aware(enabled)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "set_compression_strategy",
        description: "Set compression strategy at runtime",
        signature: "set_compression_strategy(strategy)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "set_context_window",
        description: "Set context window size at runtime",
        signature: "set_context_window(tokens)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "set_difference",
        description: "Set difference",
        signature: "set_difference(s1, s2)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "set_has",
        description: "Check set membership",
        signature: "set_has(set, item)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "set_intersection",
        description: "Set intersection",
        signature: "set_intersection(s1, s2)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "set_key",
        description: "Set key-value pair",
        signature: "set_key(dict, key, value)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "set_max_tokens",
        description: "Set max output tokens",
        signature: "set_max_tokens(4000)",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "set_max_turns",
        description: "Set max tool-calling turns",
        signature: "set_max_turns(5)",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "set_reasoning_effort",
        description: "Set reasoning effort level",
        signature: "set_reasoning_effort(\"high\")",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "set_session_dir",
        description: "Set transcript session directory at runtime",
        signature: "set_session_dir(path)",
        category: "transcript",
    },
    BuiltinCatalogEntry {
        name: "set_temperature",
        description: "Set temperature for subsequent llm act calls",
        signature: "set_temperature(0.7)",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "set_test_timeout",
        description: "Set per-test timeout",
        signature: "set_test_timeout(seconds)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "set_thinking_mode",
        description: "Enable/disable thinking mode",
        signature: "set_thinking_mode(true)",
        category: "llm",
    },
    BuiltinCatalogEntry {
        name: "set_union",
        description: "Set union",
        signature: "set_union(s1, s2)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "set_working_memory_enabled",
        description: "Enable/disable working memory at runtime",
        signature: "set_working_memory_enabled(enabled)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "sha1",
        description: "Calculate SHA1 hash",
        signature: "sha1(text)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "sha256",
        description: "Calculate SHA256 hash",
        signature: "sha256(text)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "sha512",
        description: "Calculate SHA512 hash",
        signature: "sha512(text)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "shell_exec",
        description: "Execute shell command",
        signature: "shell_exec(command, timeout?, shell?)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "shuffle",
        description: "Shuffle list randomly",
        signature: "shuffle(items)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "similarity",
        description: "String similarity",
        signature: "similarity(s1, s2)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "sin",
        description: "Sine",
        signature: "sin(radians)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "sleep",
        description: "Pause execution",
        signature: "sleep(seconds)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "some",
        description: "Check any element",
        signature: "some(lst, fn)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "sort",
        description: "Sort list",
        signature: "sort(lst, compare?)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "split",
        description: "Split string",
        signature: "split(s, sep?)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "sqrt",
        description: "Square root",
        signature: "sqrt(value)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "startswith",
        description: "Check prefix",
        signature: "startswith(s, prefix)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "stats_max",
        description: "Maximum value (stats)",
        signature: "stats_max(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "stats_min",
        description: "Minimum value (stats)",
        signature: "stats_min(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "stddev",
        description: "Standard deviation",
        signature: "stddev(numbers, population?)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "stop_recording",
        description: "Stop recording LLM interactions",
        signature: "stop_recording()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "stopwatch_elapsed",
        description: "Get elapsed time",
        signature: "stopwatch_elapsed(start_time)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "stopwatch_lap",
        description: "Get lap time",
        signature: "stopwatch_lap(start_time)",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "stopwatch_start",
        description: "Start stopwatch",
        signature: "stopwatch_start()",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "str",
        description: "Convert to string",
        signature: "str(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "stream_clear",
        description: "Clear current line",
        signature: "stream_clear()",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "stream_cursor_down",
        description: "Move cursor down",
        signature: "stream_cursor_down(n?)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "stream_cursor_up",
        description: "Move cursor up",
        signature: "stream_cursor_up(n?)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "stream_print",
        description: "Print without newline",
        signature: "stream_print(text)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "strip",
        description: "Trim whitespace",
        signature: "strip(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "substring",
        description: "Extract substring",
        signature: "substring(s, start, end?)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "sum",
        description: "Sum of numbers",
        signature: "sum(numbers)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "tan",
        description: "Tangent",
        signature: "tan(radians)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "temp_dir",
        description: "Create temp directory",
        signature: "temp_dir(suffix?, prefix?, dir?)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "temp_file",
        description: "Create temp file",
        signature: "temp_file(suffix?, prefix?, dir?)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "test_case",
        description: "Register a test case",
        signature: "test_case(name, fn)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "test_case_skip",
        description: "Register a skipped test",
        signature: "test_case_skip(name, fn?)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "test_count",
        description: "Count registered tests",
        signature: "test_count()",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "test_end_suite",
        description: "End current test suite",
        signature: "test_end_suite()",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "test_reset",
        description: "Clear all registered tests",
        signature: "test_reset()",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "test_suite",
        description: "Start a test suite",
        signature: "test_suite(name)",
        category: "test",
    },
    BuiltinCatalogEntry {
        name: "time",
        description: "Unix timestamp",
        signature: "time()",
        category: "time",
    },
    BuiltinCatalogEntry {
        name: "to_claude_parts",
        description: "Convert MediaParts to Claude content format",
        signature: "to_claude_parts(parts)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "to_gemini_parts",
        description: "Convert MediaParts to Gemini content format",
        signature: "to_gemini_parts(parts)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "to_openai_parts",
        description: "Convert MediaParts to OpenAI content format",
        signature: "to_openai_parts(parts)",
        category: "media",
    },
    BuiltinCatalogEntry {
        name: "tokenize",
        description: "Tokenize text",
        signature: "tokenize(text)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "toml_load",
        description: "Load TOML from file",
        signature: "toml_load(path)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "toml_parse",
        description: "Parse TOML",
        signature: "toml_parse(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "toml_save",
        description: "Save TOML to file",
        signature: "toml_save(path, value)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "toml_stringify",
        description: "Stringify to TOML",
        signature: "toml_stringify(value)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "trace_off",
        description: "Disable execution tracing",
        signature: "trace_off()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "trace_on",
        description: "Enable execution tracing",
        signature: "trace_on()",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "trace_value_consumers",
        description: "Trace the consumers of data produced by a message",
        signature: "trace_value_consumers(message_uuid)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "trace_value_origin",
        description: "Trace the origin of data consumed by a message",
        signature: "trace_value_origin(message_uuid)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "trim_prefix",
        description: "Remove prefix",
        signature: "trim_prefix(s, prefix)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "trim_suffix",
        description: "Remove suffix",
        signature: "trim_suffix(s, suffix)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "type",
        description: "Type name",
        signature: "type(value)",
        category: "core",
    },
    BuiltinCatalogEntry {
        name: "unique",
        description: "Remove duplicates",
        signature: "unique(lst)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "unpin_message",
        description: "Unpin a previously pinned message",
        signature: "unpin_message(uuid)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "upper",
        description: "Uppercase string",
        signature: "upper(s)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "url_build",
        description: "Build URL",
        signature: "url_build(scheme, host, path?, query?)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "url_decode",
        description: "URL decode",
        signature: "url_decode(s)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "url_encode",
        description: "URL encode",
        signature: "url_encode(s)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "url_parse",
        description: "Parse URL",
        signature: "url_parse(url)",
        category: "network",
    },
    BuiltinCatalogEntry {
        name: "uuid_from_string",
        description: "Parse UUID from string",
        signature: "uuid_from_string(s)",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "uuid_generate",
        description: "Generate UUID",
        signature: "uuid_generate()",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "uuid_nil",
        description: "Return nil UUID",
        signature: "uuid_nil()",
        category: "crypto",
    },
    BuiltinCatalogEntry {
        name: "validate_output",
        description: "Validate output against contract (json/text/schema)",
        signature: "validate_output(output, contract)",
        category: "debug",
    },
    BuiltinCatalogEntry {
        name: "values",
        description: "Get dict values",
        signature: "values(dict)",
        category: "collection",
    },
    BuiltinCatalogEntry {
        name: "variance",
        description: "Variance",
        signature: "variance(numbers, population?)",
        category: "math",
    },
    BuiltinCatalogEntry {
        name: "walk_dir",
        description: "Walk directory tree",
        signature: "walk_dir(path)",
        category: "file",
    },
    BuiltinCatalogEntry {
        name: "web_fetch",
        description: "Fetch web page content",
        signature: "web_fetch(url)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "web_search",
        description: "Search the web",
        signature: "web_search(query, limit?)",
        category: "tools",
    },
    BuiltinCatalogEntry {
        name: "word_count",
        description: "Count word frequencies",
        signature: "word_count(text)",
        category: "string",
    },
    BuiltinCatalogEntry {
        name: "working_memory_clear",
        description: "Clear all working memory",
        signature: "working_memory_clear()",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "working_memory_get",
        description: "Read working memory contents",
        signature: "working_memory_get(key?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "working_memory_remove",
        description: "Remove a working memory entry",
        signature: "working_memory_remove(key, item?)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "working_memory_set",
        description: "Set a working memory field",
        signature: "working_memory_set(key, value)",
        category: "context",
    },
    BuiltinCatalogEntry {
        name: "write_file",
        description: "Write to file",
        signature: "write_file(path, content)",
        category: "io",
    },
    BuiltinCatalogEntry {
        name: "xml_load",
        description: "Load XML from file",
        signature: "xml_load(path)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "xml_parse",
        description: "Parse XML",
        signature: "xml_parse(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "xml_save",
        description: "Save XML to file",
        signature: "xml_save(path, value, root?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "xml_stringify",
        description: "Stringify to XML",
        signature: "xml_stringify(value, root?)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "yaml_load",
        description: "Load YAML from file",
        signature: "yaml_load(path)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "yaml_parse",
        description: "Parse YAML",
        signature: "yaml_parse(text)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "yaml_save",
        description: "Save YAML to file",
        signature: "yaml_save(path, value)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "yaml_stringify",
        description: "Stringify to YAML",
        signature: "yaml_stringify(value)",
        category: "data",
    },
    BuiltinCatalogEntry {
        name: "zip",
        description: "Zip lists",
        signature: "zip(*lists)",
        category: "collection",
    },
];

/// All 351 localized aliases: alias -> canonical name.
pub static BUILTIN_ALIASES: &[(&str, &str)] = &[
    ("CPU\u6838\u5fc3\u6570", "cpu_count"),
    ("Python\u7248\u672c", "python_version"),
    ("base64\u7f16\u7801", "base64_encode"),
    ("base64\u89e3\u7801", "base64_decode"),
    ("csv\u4fdd\u5b58", "csv_save"),
    ("csv\u52a0\u8f7d", "csv_load"),
    ("csv\u5e8f\u5217\u5316", "csv_stringify"),
    ("csv\u89e3\u6790", "csv_parse"),
    ("hmac_sha256", "hmac_sha256"),
    ("html\u53cd\u8f6c\u4e49", "html_unescape"),
    ("html\u6587\u672c", "html_text"),
    ("html\u89e3\u6790", "html_parse"),
    ("html\u8f6c\u4e49", "html_escape"),
    ("html\u9009\u62e9", "html_select"),
    ("html\u94fe\u63a5", "html_links"),
    ("http\u4e0b\u8f7d", "http_download"),
    ("http\u5220\u9664", "http_delete"),
    ("http\u53d1\u5e03", "http_post"),
    ("http\u63d0\u4ea4", "http_put"),
    ("http\u83b7\u53d6", "http_get"),
    ("json\u4fdd\u5b58", "json_save"),
    ("json\u52a0\u8f7d", "json_load"),
    ("json\u5e8f\u5217\u5316", "json_stringify"),
    ("json\u89e3\u6790", "json_parse"),
    ("md5", "md5"),
    ("md\u63d0\u53d6\u6807\u9898", "markdown_extract_headings"),
    ("md\u89e3\u6790", "markdown_parse"),
    ("md\u8f6chtml", "markdown_to_html"),
    ("sha1", "sha1"),
    ("sha256", "sha256"),
    ("sha512", "sha512"),
    ("toml\u4fdd\u5b58", "toml_save"),
    ("toml\u52a0\u8f7d", "toml_load"),
    ("toml\u5e8f\u5217\u5316", "toml_stringify"),
    ("toml\u89e3\u6790", "toml_parse"),
    ("xml\u4fdd\u5b58", "xml_save"),
    ("xml\u52a0\u8f7d", "xml_load"),
    ("xml\u5e8f\u5217\u5316", "xml_stringify"),
    ("xml\u89e3\u6790", "xml_parse"),
    ("yaml\u4fdd\u5b58", "yaml_save"),
    ("yaml\u52a0\u8f7d", "yaml_load"),
    ("yaml\u5e8f\u5217\u5316", "yaml_stringify"),
    ("yaml\u89e3\u6790", "yaml_parse"),
    ("\u4e0a\u4e0b\u6587\u5207\u7247", "context_slice"),
    ("\u4e0a\u4e0b\u6587\u5360\u7528\u7387", "context_usage"),
    ("\u4e0a\u4e0b\u6587\u7edf\u8ba1", "context_stats"),
    ("\u4e2d\u4f4d\u6570", "median"),
    ("\u4e34\u65f6\u6587\u4ef6", "temp_file"),
    ("\u4e34\u65f6\u76ee\u5f55", "temp_dir"),
    ("\u4e3b\u673a\u540d", "hostname"),
    ("\u4ece\u4f4d\u7f6e\u67e5\u627e", "find_from"),
    ("\u4f11\u7720", "sleep"),
    ("\u4f17\u6570", "mode"),
    ("\u4f59\u5f26", "cos"),
    ("\u4fdd\u5b58\u5a92\u4f53", "save_media"),
    ("\u4fee\u8865\u6587\u4ef6", "patch_file"),
    ("\u503c", "values"),
    ("\u5149\u6807\u4e0a\u79fb", "stream_cursor_up"),
    ("\u5149\u6807\u4e0b\u79fb", "stream_cursor_down"),
    ("\u5168\u90e8\u6ee1\u8db3", "every"),
    ("\u5173\u95ed\u8ddf\u8e2a", "trace_off"),
    ("\u5185\u5b58\u4fe1\u606f", "memory_info"),
    ("\u5199\u6587\u4ef6", "write_file"),
    ("\u5206\u5272", "split"),
    ("\u5206\u53c9\u4e0a\u4e0b\u6587", "fork_context"),
    ("\u5206\u5757", "chunk"),
    ("\u5206\u6790\u4ee3\u7801", "analyze_code"),
    ("\u5206\u8bcd", "tokenize"),
    ("\u5217\u51fa\u4f1a\u8bdd", "list_sessions"),
    ("\u5217\u51fa\u6280\u80fd\u5f15\u7528", "list_skill_references"),
    ("\u5217\u51fa\u76ee\u5f55", "list_dir"),
    ("\u5217\u51fa\u8c03\u7528", "list_invocations"),
    ("\u5217\u8868", "list"),
    ("\u521b\u5efa\u76ee\u5f55", "mkdir"),
    ("\u5220\u9664\u4f1a\u8bdd", "delete_session"),
    ("\u5220\u9664\u5f53\u524d\u4f1a\u8bdd", "delete_current_session"),
    ("\u5220\u9664\u6587\u4ef6", "delete_file"),
    ("\u5220\u9664\u6d88\u606f", "delete_message"),
    ("\u5220\u9664\u76ee\u5f55", "delete_dir"),
    ("\u5220\u9664\u952e", "remove_key"),
    ("\u524d\u7f6e\u6240\u6709", "before_all"),
    ("\u524d\u7f6e\u6bcf\u4e2a", "before_each"),
    ("\u5254\u9664", "omit"),
    ("\u52a0\u8f7d\u6280\u80fd", "load_skill"),
    ("\u5305\u542b", "contains"),
    ("\u5305\u542b\u952e", "has_key"),
    ("\u538b\u7f29", "zip"),
    ("\u538b\u7f29\u4e0a\u4e0b\u6587", "compress_context"),
    ("\u538b\u7f29\u56de\u8c03", "on_compression"),
    ("\u538b\u7f29\u5ba1\u8ba1", "get_compression_audit"),
    ("\u53bb\u524d\u7f00", "trim_prefix"),
    ("\u53bb\u540e\u7f00", "trim_suffix"),
    ("\u53bb\u6807\u70b9", "remove_punctuation"),
    ("\u53bb\u91cd", "unique"),
    ("\u53bb\u9664\u7a7a\u767d", "strip"),
    ("\u53cd\u4f59\u5f26", "acos"),
    ("\u53cd\u6b63\u5207", "atan"),
    ("\u53cd\u6b63\u5207\u4e8c", "atan2"),
    ("\u53cd\u6b63\u5f26", "asin"),
    ("\u53cd\u8f6c", "reverse"),
    ("\u53d6\u6d88\u5927\u6a21\u578b\u8c03\u7528", "cancel_llm_call"),
    ("\u53d6\u6d88\u6240\u6709\u5927\u6a21\u578b\u8c03\u7528", "cancel_all_llm_calls"),
    ("\u53d6\u6d88\u9489\u4f4f", "unpin_message"),
    ("\u53f3\u586b\u5145", "pad_right"),
    ("\u5408\u5e76", "merge"),
    ("\u540e\u7f6e\u6240\u6709", "after_all"),
    ("\u540e\u7f6e\u6bcf\u4e2a", "after_each"),
    ("\u5411\u4e0a\u53d6\u6574", "ceil"),
    ("\u5411\u4e0b\u53d6\u6574", "floor"),
    ("\u547d\u4ee4\u884c\u53c2\u6570", "get_cli_args"),
    ("\u56db\u820d\u4e94\u5165", "round"),
    ("\u56de\u653e\u4f1a\u8bdd", "replay_transcript"),
    ("\u56de\u653e\u5b8c\u6574\u4f1a\u8bdd", "replay_full_session"),
    ("\u590d\u5236\u6587\u4ef6", "copy_file"),
    ("\u591a\u884c\u8f93\u5165", "multiline_input"),
    ("\u5931\u8d25", "fail"),
    ("\u5a92\u4f53", "media"),
    ("\u5a92\u4f53base64", "media_base64"),
    ("\u5a92\u4f53\u7c7b\u578b", "media_type"),
    ("\u5a92\u4f53\u8f6cbase64", "media_to_base64"),
    ("\u5b50\u4e32", "substring"),
    ("\u5b57\u5178", "dict"),
    ("\u5b57\u7b26", "chr"),
    ("\u5b57\u7b26\u4e32", "str"),
    ("\u5b83", "it"),
    ("\u5b89\u5168\u68c0\u67e5", "check_security"),
    ("\u5b9a\u5411\u538b\u7f29", "compress_context_target"),
    ("\u5bf9\u6570", "log"),
    ("\u5bf9\u6570\u4e8c", "log2"),
    ("\u5bf9\u6570\u5341", "log10"),
    ("\u5bfc\u5165\u4e0a\u4e0b\u6587", "import_context"),
    ("\u5bfc\u51fa\u4e0a\u4e0b\u6587", "export_context"),
    ("\u5bfc\u51fa\u4f1a\u8bdd", "export_transcript"),
    ("\u5c45\u4e2d", "center"),
    ("\u5c55\u5e73", "flatten"),
    ("\u5de6\u586b\u5145", "pad_left"),
    ("\u5df2\u9489\u4f4f\u6d88\u606f", "list_pinned_messages"),
    ("\u5e03\u5c14", "bool"),
    ("\u5e42", "pow"),
    ("\u5e73\u5747\u503c", "mean"),
    ("\u5e73\u65b9\u6839", "sqrt"),
    ("\u5e74", "date_year"),
    ("\u5f00\u542f\u8ddf\u8e2a", "trace_on"),
    ("\u5f00\u5934\u662f", "startswith"),
    ("\u5f00\u59cb\u8ba1\u65f6", "stopwatch_start"),
    ("\u5f02\u6b65\u6267\u884c", "exec_async"),
    ("\u5f52\u7ea6", "reduce"),
    ("\u5f53\u524d\u5927\u6a21\u578b\u8c03\u7528id", "current_llm_call_id"),
    ("\u5f53\u524d\u65f6\u95f4", "time"),
    ("\u5f53\u524d\u65f6\u95f4\u6233", "now"),
    ("\u6062\u590d\u4e0a\u4e0b\u6587", "restore_context"),
    ("\u6062\u590d\u4f1a\u8bdd", "resume_session"),
    ("\u6253\u5370", "print"),
    ("\u6267\u884c", "exec"),
    ("\u6267\u884c\u547d\u4ee4", "shell_exec"),
    ("\u6307\u6570", "exp"),
    ("\u6392\u5e8f", "sort"),
    ("\u63cf\u8ff0", "describe"),
    ("\u63d0\u53d6\u90ae\u7bb1", "extract_emails"),
    ("\u63d0\u53d6\u94fe\u63a5", "extract_urls"),
    ("\u63d2\u503c", "interpolate"),
    ("\u63d2\u5165\u6d88\u606f", "insert_message"),
    ("\u641c\u7d22\u4e0a\u4e0b\u6587", "search_context"),
    ("\u641c\u7d22\u4f1a\u8bdd", "search_transcript"),
    ("\u641c\u7d22\u5185\u5bb9", "grep_files"),
    ("\u64cd\u4f5c\u7cfb\u7edf", "platform"),
    ("\u6574\u6570", "int"),
    ("\u6587\u4ef6\u4fee\u6539\u65f6\u95f4", "file_modified"),
    ("\u6587\u4ef6\u54c8\u5e0c", "hash_file"),
    ("\u6587\u4ef6\u5927\u5c0f", "file_size"),
    ("\u65ad\u8a00\u4e0d\u7b49", "assert_not_equal"),
    ("\u65ad\u8a00\u4e3a\u771f", "assert_true"),
    ("\u65ad\u8a00\u5305\u542b", "assert_contains"),
    ("\u65ad\u8a00\u629b\u51fa", "assert_throws"),
    ("\u65ad\u8a00\u76f8\u7b49", "assert_equal"),
    ("\u65b9\u5dee", "variance"),
    ("\u65e5", "date_day"),
    ("\u65e5\u5fd7\u4e25\u91cd", "log_critical"),
    ("\u65e5\u5fd7\u4fe1\u606f", "log_info"),
    ("\u65e5\u5fd7\u5199\u5165\u6587\u4ef6", "log_to_file"),
    ("\u65e5\u5fd7\u8b66\u544a", "log_warn"),
    ("\u65e5\u5fd7\u8bbe\u7f6e\u7ea7\u522b", "log_set_level"),
    ("\u65e5\u5fd7\u8c03\u8bd5", "log_debug"),
    ("\u65e5\u5fd7\u9519\u8bef", "log_error"),
    ("\u65e5\u671f", "date"),
    ("\u65e5\u671f\u65f6\u95f4", "datetime"),
    ("\u65e5\u671f\u683c\u5f0f\u5316", "date_format"),
    ("\u65e5\u671f\u76f8\u51cf", "date_diff"),
    ("\u65e5\u671f\u76f8\u52a0", "date_add"),
    ("\u65e5\u671f\u89e3\u6790", "date_parse"),
    ("\u661f\u671f", "date_weekday"),
    ("\u6620\u5c04", "map"),
    ("\u662f\u5426\u6587\u4ef6", "path_is_file"),
    ("\u662f\u5426\u76ee\u5f55", "path_is_dir"),
    ("\u662f\u56fe\u7247", "is_image"),
    ("\u662f\u5a92\u4f53", "is_media"),
    ("\u662f\u89c6\u9891", "is_video"),
    ("\u662f\u97f3\u9891", "is_audio"),
    ("\u66ff\u6362", "replace"),
    ("\u66ff\u6362\u6d88\u606f", "replace_message"),
    ("\u6700\u5927\u503c", "max"),
    ("\u6700\u5c0f\u503c", "min"),
    ("\u6708", "date_month"),
    ("\u671f\u671b", "expect"),
    ("\u6761\u4ef6\u67e5\u627e", "find_if"),
    ("\u6784\u9020\u96c6\u5408", "make_set"),
    ("\u67e5\u627e", "find"),
    ("\u67e5\u627e\u6587\u4ef6", "glob_files"),
    ("\u67e5\u627e\u7d22\u5f15", "index"),
    ("\u6807\u51c6\u5dee", "stddev"),
    ("\u683c\u5f0f\u5316\u6d6e\u70b9", "format_float"),
    ("\u6b63\u5207", "tan"),
    ("\u6b63\u5219\u5206\u5272", "regex_split"),
    ("\u6b63\u5219\u5339\u914d", "regex_match"),
    ("\u6b63\u5219\u641c\u7d22", "regex_search"),
    ("\u6b63\u5219\u66ff\u6362", "regex_replace"),
    ("\u6b63\u5219\u67e5\u627e\u5168\u90e8", "regex_findall"),
    ("\u6b63\u5219\u6d4b\u8bd5", "regex_test"),
    ("\u6b63\u5f26", "sin"),
    ("\u6c42\u548c", "sum"),
    ("\u6c42\u79ef", "product"),
    ("\u6d17\u724c", "shuffle"),
    ("\u6d41\u5f0f\u6253\u5370", "stream_print"),
    ("\u6d41\u5f0f\u6e05\u9664", "stream_clear"),
    ("\u6d4b\u8bd5\u5957\u4ef6", "test_suite"),
    ("\u6d4b\u8bd5\u7528\u4f8b", "test_case"),
    ("\u6d4b\u8bd5\u8ba1\u6570", "test_count"),
    ("\u6d6e\u70b9", "float"),
    ("\u6e05\u7406\u4f1a\u8bdd", "cleanup_sessions"),
    ("\u6e05\u7a7a\u5de5\u4f5c\u8bb0\u5fc6", "working_memory_clear"),
    ("\u6e05\u9664\u4e0a\u4e0b\u6587", "clear_context"),
    ("\u6ea2\u51fa\u56de\u8c03", "on_context_overflow"),
    ("\u73af\u5883\u53d8\u91cf\u5217\u8868", "env_list"),
    ("\u73af\u5883\u53d8\u91cf\u5220\u9664", "env_delete"),
    ("\u73af\u5883\u53d8\u91cf\u83b7\u53d6", "env_get"),
    ("\u73af\u5883\u53d8\u91cf\u8bbe\u7f6e", "env_set"),
    ("\u751f\u6210UUID", "uuid_generate"),
    ("\u767e\u5206\u4f4d", "percentile"),
    ("\u76f8\u4f3c\u5ea6", "similarity"),
    ("\u76f8\u5173\u7cfb\u6570", "correlation"),
    ("\u7801\u70b9", "ord"),
    ("\u79fb\u52a8\u6587\u4ef6", "move_file"),
    ("\u79fb\u9664\u5de5\u4f5c\u8bb0\u5fc6", "working_memory_remove"),
    ("\u7a7aUUID", "uuid_nil"),
    ("\u7c7b\u578b", "type"),
    ("\u7c7b\u578b\u5224\u65ad", "isinstance"),
    ("\u7cfb\u7edf\u7248\u672c", "platform_version"),
    ("\u7ec8\u6b62\u8fdb\u7a0b", "kill"),
    ("\u7ecf\u8fc7\u65f6\u95f4", "stopwatch_elapsed"),
    ("\u7ed3\u5c3e\u662f", "endswith"),
    ("\u7ed3\u675f\u6d4b\u8bd5\u5957\u4ef6", "test_end_suite"),
    ("\u7edd\u5bf9\u503c", "abs"),
    ("\u7edf\u8ba1\u6700\u5927", "stats_max"),
    ("\u7edf\u8ba1\u6700\u5c0f", "stats_min"),
    ("\u7f16\u8f91\u8ddd\u79bb", "levenshtein"),
    ("\u7f51\u9875\u641c\u7d22", "web_search"),
    ("\u7f51\u9875\u83b7\u53d6", "web_fetch"),
    ("\u8303\u56f4", "range"),
    ("\u83b7\u53d6", "get"),
    ("\u83b7\u53d6\u4e0a\u4e0b\u6587\u914d\u7f6e", "get_context_config"),
    ("\u83b7\u53d6\u4f1a\u8bddid", "get_session_id"),
    ("\u83b7\u53d6\u4f1a\u8bdd\u5143\u6570\u636e", "get_session_meta"),
    ("\u83b7\u53d6\u4f1a\u8bdd\u6811", "get_spawn_tree"),
    ("\u83b7\u53d6\u4f1a\u8bdd\u76ee\u5f55", "get_session_dir"),
    ("\u83b7\u53d6\u5b50\u4f1a\u8bdd", "get_spawned_sessions"),
    ("\u83b7\u53d6\u5de5\u4f5c\u8bb0\u5fc6", "working_memory_get"),
    ("\u83b7\u53d6\u601d\u8003\u6a21\u5f0f", "get_thinking_mode"),
    ("\u83b7\u53d6\u63a8\u7406\u5f3a\u5ea6", "get_reasoning_effort"),
    ("\u83b7\u53d6\u63cf\u8ff0", "get_description"),
    ("\u83b7\u53d6\u63d0\u4f9b\u5546", "get_provider"),
    ("\u83b7\u53d6\u6700\u5927tokens", "get_max_tokens"),
    ("\u83b7\u53d6\u6700\u5927\u8f6e\u6b21", "get_max_turns"),
    ("\u83b7\u53d6\u6a21\u578b", "get_model"),
    ("\u83b7\u53d6\u6d88\u606f", "get_message"),
    ("\u83b7\u53d6\u6e29\u5ea6", "get_temperature"),
    ("\u83b7\u53d6\u8c03\u7528", "get_invocation"),
    ("\u83b7\u53d6\u8c03\u7528\u6811", "get_invocation_tree"),
    ("\u83b7\u53d6\u8ddf\u8e2a", "get_trace"),
    ("\u89c4\u8303\u5316\u7a7a\u767d", "normalize_whitespace"),
    ("\u89e3\u6790UUID", "uuid_from_string"),
    ("\u89e3\u6790\u547d\u4ee4\u884c\u53c2\u6570", "parse_cli_args"),
    ("\u8ba1\u6570", "count"),
    ("\u8ba1\u65f6\u5206\u6bb5", "stopwatch_lap"),
    ("\u8ba1\u7b97\u8868\u8fbe\u5f0f", "calculate"),
    ("\u8bbe\u7f6e\u4e0a\u4e0b\u6587\u7a97\u53e3", "set_context_window"),
    ("\u8bbe\u7f6e\u4f1a\u8bdd\u76ee\u5f55", "set_session_dir"),
    ("\u8bbe\u7f6e\u538b\u7f29\u7b56\u7565", "set_compression_strategy"),
    ("\u8bbe\u7f6e\u5de5\u4f5c\u8bb0\u5fc6", "working_memory_set"),
    ("\u8bbe\u7f6e\u5de5\u4f5c\u8bb0\u5fc6\u5f00\u5173", "set_working_memory_enabled"),
    ("\u8bbe\u7f6e\u601d\u8003\u6a21\u5f0f", "set_thinking_mode"),
    ("\u8bbe\u7f6e\u63a8\u7406\u5f3a\u5ea6", "set_reasoning_effort"),
    ("\u8bbe\u7f6e\u6700\u5927tokens", "set_max_tokens"),
    ("\u8bbe\u7f6e\u6700\u5927\u8f6e\u6b21", "set_max_turns"),
    ("\u8bbe\u7f6e\u6d4b\u8bd5\u8d85\u65f6", "set_test_timeout"),
    ("\u8bbe\u7f6e\u6e29\u5ea6", "set_temperature"),
    ("\u8bbe\u7f6e\u7f13\u5b58\u611f\u77e5", "set_cache_aware"),
    ("\u8bbe\u7f6e\u952e", "set_key"),
    ("\u8bcd\u9891\u7edf\u8ba1", "word_count"),
    ("\u8bfb\u6587\u4ef6", "read_file"),
    ("\u8c03\u7528\u8def\u5f84", "invocation_path"),
    ("\u8c03\u8bd5", "debug"),
    ("\u8d28\u91cf\u62a5\u544a", "quality_report"),
    ("\u8d28\u91cf\u8bc4\u5206", "quality_score"),
    ("\u8def\u5f84\u57fa\u7840\u540d", "path_basename"),
    ("\u8def\u5f84\u5b58\u5728", "path_exists"),
    ("\u8def\u5f84\u62fc\u63a5", "path_join"),
    ("\u8def\u5f84\u76ee\u5f55\u540d", "path_dirname"),
    ("\u8df3\u8fc7\u5b83", "it_skip"),
    ("\u8df3\u8fc7\u6d4b\u8bd5\u7528\u4f8b", "test_case_skip"),
    ("\u8f6cClaude\u683c\u5f0f", "to_claude_parts"),
    ("\u8f6cGemini\u683c\u5f0f", "to_gemini_parts"),
    ("\u8f6cOpenAI\u683c\u5f0f", "to_openai_parts"),
    ("\u8f6c\u5927\u5199", "upper"),
    ("\u8f6c\u5c0f\u5199", "lower"),
    ("\u8f93\u5165", "input"),
    ("\u8fc7\u6ee4", "filter"),
    ("\u8fd0\u884c\u6d4b\u8bd5", "run_tests"),
    ("\u8fd0\u884c\u6d4b\u8bd5json", "run_tests_json"),
    ("\u8fdb\u5ea6\u6761", "progress_bar"),
    ("\u8fdb\u7a0bID", "pid"),
    ("\u8fde\u63a5", "join"),
    ("\u8ffd\u52a0\u6587\u4ef6", "append_file"),
    ("\u9000\u51fa", "exit"),
    ("\u9009\u53d6", "pick"),
    ("\u9012\u5f52\u521b\u5efa\u76ee\u5f55", "mkdir_p"),
    ("\u904d\u5386\u76ee\u5f55", "walk_dir"),
    ("\u90ae\u7bb1\u9009\u62e9", "mailbox_select"),
    ("\u90e8\u5206\u6ee1\u8db3", "some"),
    ("\u91ca\u653e\u4f1a\u8bdd\u9501", "release_session_lock"),
    ("\u91cd\u590d", "repeat"),
    ("\u91cd\u7f6e\u6d4b\u8bd5", "test_reset"),
    ("\u9489\u4f4f\u5217\u8868", "list_pinned_messages"),
    ("\u9489\u4f4f\u6d88\u606f", "pin_message"),
    ("\u94fe\u63a5\u6784\u5efa", "url_build"),
    ("\u94fe\u63a5\u7f16\u7801", "url_encode"),
    ("\u94fe\u63a5\u89e3\u6790", "url_parse"),
    ("\u94fe\u63a5\u89e3\u7801", "url_decode"),
    ("\u952e", "keys"),
    ("\u952e\u503c\u5bf9", "entries"),
    ("\u957f\u5ea6", "len"),
    ("\u968f\u673a", "random"),
    ("\u968f\u673aBase64", "random_base64"),
    ("\u968f\u673a\u5341\u516d\u8fdb\u5236", "random_hex"),
    ("\u968f\u673a\u5b57\u8282", "random_bytes"),
    ("\u968f\u673a\u62bd\u6837", "sample"),
    ("\u968f\u673a\u6574\u6570", "randint"),
    ("\u968f\u673a\u9009\u62e9", "choice"),
    ("\u96c6\u5408\u4ea4", "set_intersection"),
    ("\u96c6\u5408\u5305\u542b", "set_has"),
    ("\u96c6\u5408\u5dee", "set_difference"),
    ("\u96c6\u5408\u5e76", "set_union"),
];
